name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Install docker
      run: |
           curl -fsSL https://get.docker.com -o get-docker.sh
           sh get-docker.sh
    - name: Show docker version
      run:  docker --version
    - name: Login to docker registry
      run:  docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_PASS }}
    - name: Build the image
      run:  docker build -t dancier/dancer:1.0 .
    - name: Publish the image
      run:  docker push dancier/dancer:1.0
    - name: Install hetzner cloud api
      run:  |
            sudo apt -y install python3-pip
            sudo apt -y install python3-setuptools
            sudo -H pip3 install hcloud
    - name: Create ssh key
      run: echo ${{ secrets.DEPLOY_KEY }} >> /root/dancier
