name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Install docker
      run: |
           curl -fsSL https://get.docker.com -o get-docker.sh
           sh get-docker.sh
    - name: Show docker version
      run:  docker --version
    - name: Login to docker registry (from github)
      run:  docker login docker.pkg.github.com --username gorzala --password {{{{secrets.GITHUB_TOKEN}}}}
    - name: Build the image
      run:  docker build -t docker.pkg.github.com/dancier/dancer/dancer:1.0 .
